[package]
name = "clap-man-example"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive", "cargo", "env"] }
clap_complete = "3"

[build-dependencies]
clap = { version = "3", features = ["derive", "cargo", "env"] }
clap_complete = "3"
clap_mangen = "0.1"
